\contentsline {firstline}{\chapternumberline {1} Pharitvāna mettaṃ samettā bhadantā}{16}{chapter.7}%
\contentsline {firstline}{\chapternumberline {1} Samantā cakka-vāḷesu}{16}{chapter.7}%
\contentsline {firstline}{\chapternumberline {1} Namo tassa Bhagavato}{17}{chapter.8}%
\contentsline {firstline}{\chapternumberline {1} Buddhaṃ saraṇaṃ gacchāmi}{17}{chapter.9}%
\contentsline {firstline}{\chapternumberline {1} Yo cakkhumā moha-malāpakaṭṭho}{18}{chapter.10}%
\contentsfinish 
