\contentsline {firstline}{\chapternumberline {1} อิมินา ปุญญะกัมเมนะ}{34}{chapter.23}%
\contentsline {firstline}{\chapternumberline {1} ปุญญัสสิ’ทานิ}{37}{chapter.25}%
\contentsline {firstline}{\chapternumberline {1} กะระณียะมัตถะกุสะเลนะ}{39}{chapter.26}%
\contentsline {firstline}{\chapternumberline {1} ธฺีส อีส ว็อท ชูล์ด บี ดัน}{41}{chapter.27}%
\contentsline {firstline}{\chapternumberline {1} อะหัง สุขิโต โหมิ}{42}{chapter.28}%
\contentsline {firstline}{\chapternumberline {1} เมย์ ไอ อบายด์ อิน เววล์-บีอิง}{43}{chapter.29}%
\contentsline {firstline}{\chapternumberline {1} เมตตา-สะหะคะเตนะ}{45}{chapter.30}%
\contentsline {firstline}{\chapternumberline {1} ไอ วิวล์ อ๎บายด์}{46}{chapter.31}%
\contentsfinish 
