[book]
title = "Livro de Cânticos"
authors = ["Forest Sangha"]
language = "pt"
multilingual = false
src = "."

[build]
build-dir = "../../../dist/pt"
create-missing = true

[output.epub]
additional-css = ["../../../assets/css/output-epub.css"]
epub-version = 3
use-default-css = false
no-section-label = true
footnote-backrefs = true
curly-quotes = true
cover-image = "images/pt-webcover.jpg"
additional-resources = ["fonts/GentiumIncantation-Regular.ttf", "fonts/GentiumIncantation-Italic.ttf", "fonts/Ubuntu-X-Medium.ttf", "images/chanting-buddho.png", "images/chanting-anicca.png", "images/yo-so-bhagava.png"]
